services:
  - type: web
    name: html5
    env: node
    buildCommand: npm install
    startCommand: npx http-server email-list/src/main/webapp -p $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
