services:
  - type: web
    name: html5
    env: node
    buildCommand: npm install
    startCommand: npx http-server . -p $PORT --cors
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
